apiVersion: v1
kind: Service
metadata:
 name: db
spec:
 ports:
 - port: 3306
 selector:
    app: db
---
apiVersion: apps/v1dep
kind: Deployment
metadata:
 name: db
spec:
 replicas: 1
 selector:
    matchLabels:
      app: db
 template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: jacek010/budgetapp-db:latest
---
apiVersion: v1
kind: Service
metadata:
 name: backend
spec:
 ports:
 - port: 8000
 selector:
    app: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: backend
spec:
 replicas: 1
 selector:
    matchLabels:
      app: backend
 template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: jacek010/budgetapp-backend:latest
---
apiVersion: v1
kind: Service
metadata:
 name: frontend
spec:
 type: LoadBalancer
 ports:
 - port: 3000
 selector:
    app: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: frontend
spec:
 replicas: 1
 selector:
    matchLabels:
      app: frontend
 template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: jacek010/budgetapp-frontend:latest
