version: '3.8'
services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
  backend:
    image: python:3.9
    command: bash -c "pip install -r /backend/requirements.txt && uvicorn main:app --host 0.0.0.0 --port 80"
    volumes:
      - ./backend:/backend
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql://${DB_USER}:${DB_PASSWORD}@db:3306/${DB_NAME}
  frontend:
    image: node:14
    command: bash -c "npm install && npm run build && npm start"
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend
volumes:
  db_data: {}
