version: '3.8'
services:
  db:
    image: jacek010/mysql:latest
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=caching_sha2_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - "./db/init.sql:/docker-entrypoint-initdb.d/init.sql"
  backend:
    image: jacek010/python:latest
    working_dir: /backend/
    command: bash -c "pip install -r requirements.txt && uvicorn main:app --host 0.0.0.0 --port 8000"
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql://${DB_USER}:${DB_PASSWORD}@db:3306/${DB_NAME}
  frontend:
    image: jacek010/node:latest
    working_dir: /app/
    command: bash -c "npm install && npm run build && npm start"
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend
      
