version: '3.x'
services:
  db:
    build: 
      context: .
      dockerfile: Dockerfile.db
    restart: always
    image: ${REPO}-db:${VERSION_TAG}
  backend:
    build: 
      context: .
      dockerfile: Dockerfile.backend
    image: ${REPO}-backend:${VERSION_TAG}
    ports:
      - "8000:8000"
    depends_on:
      - db
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile.frontend
    image: ${REPO}-frontend:${VERSION_TAG}
    depends_on:
      - backend