# Dockerfile.db
FROM mysql:latest
CMD ["--default-authentication-plugin=caching_sha2_password"]
ENV MYSQL_ROOT_PASSWORD ${DB_ROOT_PASSWORD}
ENV MYSQL_DATABASE ${DB_NAME}
ENV MYSQL_USER ${DB_USER}
ENV MYSQL_PASSWORD ${DB_PASSWORD}
COPY ./db/init.sql /docker-entrypoint-initdb.d/init.sql
EXPOSE 3306