# Dockerfile.backend
FROM python:latest
WORKDIR /backend/
COPY /backend /backend
RUN pip install -r requirements.txt
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
ENV DATABASE_URL = mysql://${DB_USER}:${DB_PASSWORD}@db:3306/${DB_NAME}
EXPOSE 8000