name: Build and Push Docker Images to Docker Hub

on:
 push:
    branches: [ "main" ]

env:
 REGISTRY: jacek010
 IMAGE_NAME: my-budget-app

jobs:
 build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker images
        run: docker compose build
      - name: Push Docker images
        run: scripth.sh
